apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-app
  namespace: argocd
spec:
  description: GitOps project for the sample app workshop
  sourceRepos:
    - https://github.com/andriimazurslalom/eks-workshop.git
  destinations:
    - namespace: sample-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
