replicaCount: 1

image:
  repository: 306536996258.dkr.ecr.eu-central-1.amazonaws.com/sample-app
  tag: "0.8.0-test"

service:
  type: ClusterIP

config:
  appEnv: dev
  logLevel: info

ingress:
  tls:
    - secretName: sample-app-selfsigned-tls
      hosts:
        - sample-app.local
