apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secrets
  namespace: sample-app
type: Opaque
stringData:
  DATABASE_URL: CHANGEME_DATABASE_URL
  JWT_SECRET: CHANGEME_JWT_SECRET
  THIRD_PARTY_API_KEY: CHANGEME_THIRD_PARTY_API_KEY
