apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sample-app
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 198.51.100.24/32
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
